### ISSUE TITLE
Make a release?

### ISSUE THREAD

**Issue by Ramblurr** [ArtBIT/generator-luxe#2]
~~The [recent commit](https://github.com/ArtBIT/generator-luxe/commit/bddce66517ccefa2bdcb296c865a15a30bc9f777#diff-fec2bcd5907552892bad37b02553ff55R21) that updates the generator for changes in the API seems to be premature, as the generated code doesn't compile on the stable version of luxe installed with `haxelib run snowfall update luxe`.~~

Sorry ignore all that. The problem is that the published version of the generator in npm isn't up to date. Any chance you could make a release?

**Comment by ArtBIT** [comment]
Done!
